<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php'; require_once __DIR__ . '/square_sync.php'; require_once __DIR__ . '/square_webhook_lib.php';
if (!squareWebhookIsPrivateRequest()) { http_response_code(403); header('Content-Type: text/plain; charset=utf-8'); echo 'Forbidden'; exit; }
ensureStorageWritable(); $pdo = pdoConnect(__DIR__ . '/data/intake.sqlite'); squareWebhookEnsureSchema($pdo); $cfg = squareWebhookConfig();
function whEsc(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function whCount(PDO $pdo, ?string $status = null): int { $q = $status === null ? 'SELECT COUNT(*) FROM square_webhook_events' : 'SELECT COUNT(*) FROM square_webhook_events WHERE processing_status=:s'; $s=$pdo->prepare($q); $s->execute($status === null ? [] : ['s'=>$status]); return (int)$s->fetchColumn(); }
$events=$pdo->query('SELECT event_id,event_type,received_at,processed_at,processing_status,retry_count,error_message FROM square_webhook_events ORDER BY received_at DESC LIMIT 50')->fetchAll();
$sales=$pdo->query('SELECT square_payment_id,square_order_id,payment_status,amount_cents,currency,recorded_at FROM square_sales ORDER BY recorded_at DESC LIMIT 50')->fetchAll();
$warnings=$pdo->query("SELECT * FROM square_inventory_events WHERE reconciliation_status='warning' ORDER BY received_at DESC LIMIT 50")->fetchAll();
$lastLog=is_file(__DIR__.'/logs/square_webhook.log') ? implode("\n", array_slice(file(__DIR__.'/logs/square_webhook.log', FILE_IGNORE_NEW_LINES) ?: [], -50)) : '';
$last24=(int)$pdo->query("SELECT COUNT(*) FROM square_webhook_events WHERE received_at >= datetime('now','-24 hours')")->fetchColumn(); $last=(string)$pdo->query('SELECT MAX(received_at) FROM square_webhook_events')->fetchColumn();
?><!doctype html><meta charset="utf-8"><title>Square webhook status</title><style>body{font:14px system-ui;margin:2rem}table{border-collapse:collapse;width:100%;margin:1rem 0}td,th{border:1px solid #ccc;padding:.4rem;text-align:left}pre{white-space:pre-wrap;background:#eee;padding:1rem}.warn{color:#a00}</style>
<h1>Square webhook status</h1><p class="<?= $cfg['notification_url'] === '' ? 'warn' : '' ?>">Enabled: <?= $cfg['enabled'] ? 'yes' : 'no' ?> · Signature key configured: <?= $cfg['signature_key'] !== '' ? 'yes' : 'no' ?> · Notification URL: <?= whEsc($cfg['notification_url'] ?: 'missing') ?></p><p class="<?= squareSyncConfig()['enabled'] ? '' : 'warn' ?>">Square API configured: <?= squareSyncConfig()['enabled'] ? 'yes' : 'no' ?></p>
<p>Total <?= whCount($pdo) ?> · Processed <?= whCount($pdo,'processed') ?> · Failed <?= whCount($pdo,'failed') ?> · Ignored <?= whCount($pdo,'ignored') ?> · Last 24h <?= $last24 ?> · Latest <?= whEsc($last ?: 'none') ?></p>
<h2>Recent events</h2><table><tr><th>ID</th><th>Type</th><th>Status</th><th>Received</th><th>Error</th></tr><?php foreach($events as $r): ?><tr><td><?=whEsc($r['event_id'])?></td><td><?=whEsc($r['event_type'])?></td><td><?=whEsc($r['processing_status'])?></td><td><?=whEsc($r['received_at'])?></td><td><?=whEsc($r['error_message'])?></td></tr><?php endforeach ?></table>
<h2>Recent sales</h2><table><tr><th>Payment</th><th>Order</th><th>Status</th><th>Amount</th><th>Recorded</th></tr><?php foreach($sales as $r): ?><tr><td><?=whEsc($r['square_payment_id'])?></td><td><?=whEsc($r['square_order_id'])?></td><td><?=whEsc($r['payment_status'])?></td><td><?=whEsc($r['amount_cents'].' '.$r['currency'])?></td><td><?=whEsc($r['recorded_at'])?></td></tr><?php endforeach ?></table>
<h2>Reconciliation warnings</h2><table><tr><th>Variation</th><th>SKU</th><th>Quantity</th><th>Note</th></tr><?php foreach($warnings as $r): ?><tr><td><?=whEsc($r['square_variation_id'])?></td><td><?=whEsc($r['sku_normalized'])?></td><td><?=whEsc($r['quantity'])?></td><td><?=whEsc($r['notes'])?></td></tr><?php endforeach ?></table><h2>Recent log</h2><pre><?=whEsc($lastLog)?></pre>
